### ISSUE TITLE
RRV08 - Define Recipe Filters (1)

### ISSUE THREAD

**Issue by Theauxm** [Theauxm/Pantree#8]
**Basic feature description:**
- Adds recipe filters such as Breakfast, Healthy, Mediterranean, Chinese, etc.. along with cooking filters such as Minimal Prep Time, Under 30 Mins, etc..

**Branch for development:**
- RRV/08_RECIPE_FILTERS

**Risk factors (what modules or other features could be broken/affected by this fix):**
- None

**Priority (High, Medium, Low):**
 - Medium

**Points (1, 2, 3, 5, 8, 13):**
- 1

**Sprint Cycle (Date started):**
 - August 30th 2021

**Task depends on (Other dependant tasks):**
- RRV07

**Comment by Theauxm** [comment]
**Basic feature description:**
- [This Filter flow](https://drive.google.com/file/d/1bdg_iDoFrkYCzJPPGW8FgQx_SsDUkUPQ/view?usp=sharing) document shows the flow between buttons on the UI, which can be referenced via [RRV08](https://github.com/Theauxm/Pantree/issues/8). The top level defines filtering by recipe type, or search bar recipe name. The mid level specifies which filters are available, and the bottom level defines which recipes to show. 

**Branch for testing:**
- None

**Risk factors (what modules or other features could be broken/affected by this fix):**
- Database will need to be changed to move forward with this schema

**Recommendations for Testing:**
 - Look over the document, think of any potential flaws in logic or additional edge cases I am missing with filters. May be able to reduce complexity or database reads per pipeline. 
 
**Recommendations for Code Review:**
- None, it isn't code

**Descriptions of unit-tests ran by developers before submitting the ticket:**
- None

**Comment by Brandon-Wong801** [comment]
Looks good! May suggest separating the user flow so it is more apparent that they can choose one, or multiple filters.
